date.timezone = Europe/Paris
short_open_tag = Off

# Optimize memory management
memory_limit= 2048M
upload_max_filesize = 32M
post_max_size = 40M

realpath_cache_size = 4096K
realpath_cache_ttl = 600
max_input_time = 120
max_execution_time = 600

# Activation des logs
error_log = /var/log/php_errors.log
log_errors = On
