opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=32
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0
opcache.revalidate_freq=60
opcache.max_wasted_percentage=10
opcache.fast_shutdown=1

# http://symfony.com/doc/current/performance.html
opcache.preload=${OPCACHE_PRELOAD}
opcache.preload_user=www-data