### Authentification
POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "email": "manager@balto.fr",
    "password": "manager@balto.fr"
}

### Voir mes infos
@meUuid = 019f652f-08cf-76cb-8d6b-9b411f77516b
GET {{baseUrl}}/api/me
Authorization: Bearer {{Security.token}}

### Refresh le token
POST {{baseUrl}}/api/token/refresh
Content-Type: application/json

{
    "refresh_token": "{{Security.refreshToken}}"
}

### Dashboard
GET {{baseUrl}}/api/dashboard
Content-Type: application/json
Authorization: Bearer {{Security.token}}


### Création d'un client
POST {{baseUrl}}/api/customers
Content-Type: application/json
Authorization: Bearer {{Security.token}}

{
    "firstname": "Igor 2",
    "lastname": "GAMATH",
    "phone": "+33650102835",
    "note": "Client créé depuis un fichier .http"
}


### Récupérer les clients du shop auquel appartient le user connecté
GET {{baseUrl}}/api/customers
Accept: application/json
Authorization: Bearer {{Security.token}}


### Récupérer un client par son UUID ou ID
@customerId = 104
@customerUuid = 019f901f-5600-7e34-9fb1-5f689c8e4d8a
@customerUuidOrId = {{customerId}}
GET {{baseUrl}}/api/customers/{{customerUuidOrId}}
Accept: application/json
Authorization: Bearer {{Security.token}}


### Liste des opération d'un client
GET {{baseUrl}}/api/ledgers/customers/{{customerUuid}}/ledger
Accept: application/json
Authorization: Bearer {{Security.token}}

### Liste des opération d'un client V2
GET {{baseUrl}}/api/ledgers/customers/{{customerUuid}}/ledger-v2
Accept: application/json
Authorization: Bearer {{Security.token}}


### Création d'une dette au client
POST {{baseUrl}}/api/ledgers/customers/{{customerUuid}}/debts
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Security.token}}

{
    "amountInCents": 1500,
    "description": "Dette pour une palette d'eau christaline de la facture #12345",
    "occurredAt": "2026-07-14T10:30:00+02:00"
}

### Création d'un paiement de dette pour client
POST {{baseUrl}}/api/ledgers/customers/{{customerUuid}}/payments
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Security.token}}

{
    "amountInCents": 1000,
    "paymentMethod": "CASH",
    "occurredAt": "2026-07-15T00:30:00+02:00"
}

### Corriger un paiement de dette pour client
@ledgerUuid = 019f7586-277f-75dc-b913-10886eb5a58b
POST {{baseUrl}}/api/ledgers/{{ledgerUuid}}/correct
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Security.token}}

{
    "amountInCents": 500,
    "paymentMethod": "CASH",
    "description": "Correction du paiement précédent. La facture #12345",
    "occurredAt": "2026-07-15T00:30:00+02:00"
}

### Annuler une dette client
POST {{baseUrl}}/api/ledgers/{{ledgerUuid}}/reverse
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Security.token}}

{

}
