api_controllers:
    resource:
        path: ../src/Controller/RestApi/
        namespace: App\Controller\RestApi
    type: attribute
    prefix: /api
    name_prefix: api_

api_login_check:
    path: /api/login
